# Generated by Django 3.2.5 on 2021-07-19 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistMarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
        migrations.AddField(
            model_name='artwork',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 7, 19)),
        ),
        migrations.AddField(
            model_name='artwork',
            name='published_date',
            field=models.DateField(default=datetime.date(2021, 7, 19)),
        ),
    ]
