# Generated by Django 3.2.5 on 2021-07-19 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artistMarket', '0002_auto_20210719_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 0, 32, 32, 744967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
