# Generated by Django 3.2.5 on 2021-07-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistMarket', '0003_auto_20210719_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcollection',
            name='collection_types',
            field=models.CharField(choices=[('album', 'Album'), ('collection', 'Collection'), ('show', 'Show'), ('suite', 'Suite'), ('bag', 'Bag')], default='collection', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_date',
            field=models.DateField(),
        ),
    ]
