# Generated by Django 3.2.5 on 2021-07-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistMarket', '0004_auto_20210719_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/images/'),
        ),
    ]
