# Generated by Django 3.2.5 on 2021-07-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
